version: "3"
services:
  nas-tools:
    image: jxxghp/nas-tools:latest
    ports:
      - 3000:3000        # 預設的webui控制埠
    volumes:
      - ./config:/config   # 冒號左邊請修改為你想儲存配置的路徑
      - /你的媒體目錄:/你想設定的容器內能見到的目錄   # 媒體目錄，多個目錄需要分別對映進來，需要滿足配置檔案說明中的要求
    environment: 
      - PUID=0    # 想切換為哪個使用者來執行程式，該使用者的uid
      - PGID=0    # 想切換為哪個使用者來執行程式，該使用者的gid
      - UMASK=000 # 掩碼許可權，預設000，可以考慮設定為022
      - NASTOOL_AUTO_UPDATE=false  # 如需在啟動容器時自動升級程程式請設定為true
     #- REPO_URL=https://ghproxy.com/https://github.com/kindomLee/nas-tools.git  # 當你訪問github網路很差時，可以考慮解釋本行註釋
    restart: always
    network_mode: bridge
    hostname: nas-tools
    container_name: nas-tools